steps:
  - name: gcr.io/cloud-builders/docker
    env:
      - DOCKER_BUILDKIT=1
    args:
      - build
      - --progress=plain
      - -t
      - us-central1-docker.pkg.dev/project-ce74a06d-c017-4712-8f0/jogga/jogga:latest
      - .

images:
  - us-central1-docker.pkg.dev/project-ce74a06d-c017-4712-8f0/jogga/jogga:latest

options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY

timeout: 3600s
