-- jogga sovereign-mode schema (SQLite, single owner).
-- Translated from the multi-user fedisport PostgreSQL schema.
--
-- Differences from the multi-user version:
--   - SQLite syntax: TEXT PKs (UUIDs generated app-side), TEXT for JSON/array,
--     INTEGER for booleans, TEXT for timestamps (ISO-8601 UTC with millisecond precision).
--   - Single owner: no `local_clubs`, no `club_roles`, no `is_admin`,
--     no `show_in_directory`. The owner can still join *remote* clubs.
--   - No GIN/array indexes (SQLite does not support them).
--
-- UUIDs are generated by the application (`uuid::Uuid::new_v4()` /
-- `uuid::Uuid::now_v7()` in the server layer); the schema only enforces
-- `TEXT PRIMARY KEY NOT NULL`.
--
-- Timestamps default to ISO-8601 UTC with millisecond precision so they
-- round-trip cleanly through `chrono::DateTime<Utc>` in sqlx.

PRAGMA foreign_keys = ON;


CREATE TABLE actors (
    id                          TEXT PRIMARY KEY NOT NULL,
    ap_id                       TEXT NOT NULL UNIQUE,
    username                    TEXT NOT NULL,
    domain                      TEXT NOT NULL,
    actor_type                  TEXT NOT NULL DEFAULT 'Person',
    display_name                TEXT,
    summary                     TEXT,
    public_key_pem              TEXT NOT NULL,
    private_key_pem             TEXT,          -- NULL for remote actors
    inbox_url                   TEXT NOT NULL,
    outbox_url                  TEXT NOT NULL,
    followers_url               TEXT NOT NULL,
    following_url               TEXT NOT NULL,
    shared_inbox_url            TEXT,
    manually_approves_followers INTEGER NOT NULL DEFAULT 0,
    is_local                    INTEGER NOT NULL DEFAULT 0,
    is_suspended                INTEGER NOT NULL DEFAULT 0,
    avatar_url                  TEXT,
    -- JSONB → TEXT (JSON-encoded). NULL allowed for partial remote rows.
    ap_json                     TEXT,
    -- TEXT[] → TEXT (JSON array). Default '[]' = empty list.
    also_known_as               TEXT NOT NULL DEFAULT '[]',
    moved_to                    TEXT,
    created_at                  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at                  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    UNIQUE (username, domain)
);

CREATE INDEX actors_domain_idx   ON actors (domain);
CREATE INDEX actors_is_local_idx ON actors (is_local);
CREATE INDEX actors_username_idx ON actors (username) WHERE is_local = 1;


CREATE TABLE objects (
    id            TEXT PRIMARY KEY NOT NULL,
    ap_id         TEXT NOT NULL UNIQUE,
    object_type   TEXT NOT NULL,
    attributed_to TEXT NOT NULL,
    actor_id      TEXT REFERENCES actors(id) ON DELETE CASCADE,
    content       TEXT,
    content_map   TEXT,           -- JSONB → TEXT (JSON)
    summary       TEXT,
    sensitive     INTEGER NOT NULL DEFAULT 0,
    in_reply_to   TEXT,
    published     TEXT,
    url           TEXT,
    visibility    TEXT NOT NULL DEFAULT 'public'
                      CHECK (visibility IN ('public', 'unlisted', 'followers', 'private')),
    reply_count   INTEGER NOT NULL DEFAULT 0,
    ap_json       TEXT NOT NULL,  -- JSONB NOT NULL → TEXT NOT NULL
    created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE INDEX objects_actor_id_idx       ON objects (actor_id);
CREATE INDEX objects_published_idx      ON objects (published DESC);
CREATE INDEX objects_in_reply_to_idx    ON objects (in_reply_to) WHERE in_reply_to IS NOT NULL;
CREATE INDEX objects_attributed_to_idx  ON objects (attributed_to);
CREATE INDEX objects_type_published_idx ON objects (object_type, published DESC);

-- Reply-count maintenance.
CREATE TRIGGER trg_reply_count_insert
AFTER INSERT ON objects
FOR EACH ROW
WHEN NEW.in_reply_to IS NOT NULL
BEGIN
    UPDATE objects
    SET reply_count = reply_count + 1
    WHERE ap_id = NEW.in_reply_to;
END;

CREATE TRIGGER trg_reply_count_delete
AFTER DELETE ON objects
FOR EACH ROW
WHEN OLD.in_reply_to IS NOT NULL
BEGIN
    UPDATE objects
    SET reply_count = reply_count - 1
    WHERE ap_id = OLD.in_reply_to;
END;


CREATE TABLE activities (
    id              TEXT PRIMARY KEY NOT NULL,
    ap_id           TEXT NOT NULL UNIQUE,
    activity_type   TEXT NOT NULL,
    actor_id        TEXT NOT NULL REFERENCES actors(id) ON DELETE CASCADE,
    object_ap_id    TEXT NOT NULL,
    target_ap_id    TEXT,
    object_id       TEXT REFERENCES objects(id) ON DELETE CASCADE,
    ap_json         TEXT NOT NULL,
    published       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE INDEX activities_actor_id_idx     ON activities (actor_id);
CREATE INDEX activities_type_idx         ON activities (activity_type);
CREATE INDEX activities_published_idx    ON activities (published DESC);
CREATE INDEX activities_object_ap_id_idx ON activities (object_ap_id);


CREATE TABLE followers (
    id            TEXT PRIMARY KEY NOT NULL,
    actor_id      TEXT NOT NULL REFERENCES actors(id) ON DELETE CASCADE,
    follower_id   TEXT NOT NULL REFERENCES actors(id) ON DELETE CASCADE,
    follow_ap_id  TEXT,
    accepted      INTEGER NOT NULL DEFAULT 1,
    created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    UNIQUE (actor_id, follower_id)
);

CREATE INDEX followers_actor_id_idx    ON followers (actor_id);
CREATE INDEX followers_follower_id_idx ON followers (follower_id);

CREATE TABLE following (
    id         TEXT PRIMARY KEY NOT NULL,
    actor_id   TEXT NOT NULL REFERENCES actors(id) ON DELETE CASCADE,
    target_id  TEXT NOT NULL REFERENCES actors(id) ON DELETE CASCADE,
    accepted   INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    UNIQUE (actor_id, target_id)
);

CREATE INDEX following_actor_id_idx  ON following (actor_id);
CREATE INDEX following_target_id_idx ON following (target_id);


CREATE TABLE inbox_items (
    id          TEXT PRIMARY KEY NOT NULL,
    owner_id    TEXT NOT NULL REFERENCES actors(id) ON DELETE CASCADE,
    activity_id TEXT NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
    read_at     TEXT,
    created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    UNIQUE (owner_id, activity_id)
);

CREATE INDEX inbox_owner_created_idx ON inbox_items (owner_id, created_at DESC);

CREATE TABLE outbox_items (
    id          TEXT PRIMARY KEY NOT NULL,
    owner_id    TEXT NOT NULL REFERENCES actors(id) ON DELETE CASCADE,
    activity_id TEXT NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
    created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    UNIQUE (owner_id, activity_id)
);

CREATE INDEX outbox_owner_created_idx ON outbox_items (owner_id, created_at DESC);

-- In sovereign mode the table holds at most one row.  `is_admin` and
-- `show_in_directory` are dropped — the lone account is always the owner,
-- and there is no directory feature.

CREATE TABLE local_accounts (
    id                TEXT PRIMARY KEY NOT NULL,
    actor_id          TEXT NOT NULL UNIQUE REFERENCES actors(id) ON DELETE CASCADE,
    password_hash     TEXT NOT NULL,
    api_token         TEXT NOT NULL UNIQUE,
    email             TEXT UNIQUE,
    phone             TEXT UNIQUE,
    email_verified    INTEGER NOT NULL DEFAULT 0,
    phone_verified    INTEGER NOT NULL DEFAULT 0,
    public_profile    INTEGER NOT NULL DEFAULT 1,
    theme             TEXT NOT NULL DEFAULT 'dark',
    created_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE INDEX local_accounts_api_token_idx ON local_accounts (api_token);
CREATE INDEX local_accounts_email_idx     ON local_accounts (email) WHERE email IS NOT NULL;
CREATE INDEX local_accounts_phone_idx     ON local_accounts (phone) WHERE phone IS NOT NULL;


CREATE TABLE otp_requests (
    id           TEXT PRIMARY KEY NOT NULL,
    contact      TEXT NOT NULL,
    contact_type TEXT NOT NULL CHECK (contact_type IN ('email', 'phone')),
    purpose      TEXT NOT NULL CHECK (purpose IN ('registration', 'password_reset')),
    username     TEXT,
    code_hash    TEXT NOT NULL,
    expires_at   TEXT NOT NULL,
    used_at      TEXT,
    created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE INDEX otp_requests_contact_purpose_idx
    ON otp_requests (contact, purpose)
    WHERE used_at IS NULL;

CREATE INDEX otp_requests_expires_at_idx ON otp_requests (expires_at);


CREATE TABLE exercises (
    id                  TEXT PRIMARY KEY NOT NULL,
    actor_id            TEXT NOT NULL REFERENCES actors(id) ON DELETE CASCADE,
    object_id           TEXT NOT NULL REFERENCES objects(id) ON DELETE CASCADE,
    activity_type       TEXT NOT NULL CHECK (activity_type IN ('run', 'ride', 'swim', 'walk', 'hike')),
    started_at          TEXT NOT NULL,
    duration_s          INTEGER NOT NULL,
    distance_m          REAL NOT NULL,
    elevation_gain_m    REAL,
    avg_pace_s_per_km   REAL,
    avg_heart_rate_bpm  INTEGER,
    max_heart_rate_bpm  INTEGER,
    avg_cadence_rpm     REAL,
    avg_power_w         REAL,
    max_power_w         REAL,
    normalized_power_w  REAL,
    device              TEXT,
    title               TEXT,
    -- JSONB → TEXT (JSON-encoded GeoJSON)
    route               TEXT,
    gpx_url             TEXT,
    file_type           TEXT NOT NULL DEFAULT 'gpx'
                            CHECK (file_type IN ('gpx', 'fit', 'manual')),
    visibility          TEXT NOT NULL DEFAULT 'public'
                            CHECK (visibility IN ('public', 'followers', 'private')),
    -- TEXT[] → TEXT (JSON array, default empty list).
    hidden_stats        TEXT NOT NULL DEFAULT '[]',
    created_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE INDEX exercises_actor_id_idx        ON exercises (actor_id);
CREATE INDEX exercises_started_at_idx      ON exercises (started_at DESC);
CREATE UNIQUE INDEX exercises_object_id_idx ON exercises (object_id);


CREATE TABLE likes (
    id           TEXT PRIMARY KEY NOT NULL,
    actor_ap_id  TEXT NOT NULL,
    object_ap_id TEXT NOT NULL,
    like_ap_id   TEXT NOT NULL UNIQUE,
    created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE UNIQUE INDEX likes_actor_object_idx ON likes (actor_ap_id, object_ap_id);
CREATE INDEX likes_object_ap_id_idx        ON likes (object_ap_id);

CREATE TABLE announces (
    id              TEXT PRIMARY KEY NOT NULL,
    actor_ap_id     TEXT NOT NULL,
    object_ap_id    TEXT NOT NULL,
    announce_ap_id  TEXT NOT NULL UNIQUE,
    created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE UNIQUE INDEX announces_actor_object_idx ON announces (actor_ap_id, object_ap_id);
CREATE INDEX announces_object_ap_id_idx        ON announces (object_ap_id);
CREATE INDEX announces_actor_ap_id_idx         ON announces (actor_ap_id);


CREATE TABLE media_attachments (
    id           TEXT PRIMARY KEY NOT NULL,
    object_ap_id TEXT NOT NULL REFERENCES objects(ap_id) ON DELETE CASCADE,
    url          TEXT NOT NULL,
    media_type   TEXT NOT NULL DEFAULT 'image/jpeg',
    caption      TEXT,
    position     INTEGER NOT NULL DEFAULT 0,
    created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE INDEX media_attachments_object_idx ON media_attachments (object_ap_id, position);


CREATE TABLE outbox_deliveries (
    id              TEXT PRIMARY KEY NOT NULL,
    activity_id     TEXT NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
    inbox_url       TEXT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending', 'success', 'failed', 'permanent_fail')),
    attempt_count   INTEGER NOT NULL DEFAULT 0,
    last_attempt_at TEXT,
    last_error      TEXT,
    next_retry_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    UNIQUE (activity_id, inbox_url)
);

CREATE INDEX outbox_deliveries_pending_idx
    ON outbox_deliveries (next_retry_at)
    WHERE status IN ('pending', 'failed');


CREATE TABLE notifications (
    id            TEXT PRIMARY KEY NOT NULL,
    actor_id      TEXT NOT NULL REFERENCES actors(id) ON DELETE CASCADE,
    kind          TEXT NOT NULL
                    CHECK (kind IN ('follow_request', 'new_follower', 'follow_accepted', 'like', 'reply')),
    from_actor_id TEXT NOT NULL REFERENCES actors(id) ON DELETE CASCADE,
    object_ap_id  TEXT,
    object_title  TEXT,
    is_read       INTEGER NOT NULL DEFAULT 0,
    is_dismissed  INTEGER NOT NULL DEFAULT 0,
    created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    UNIQUE (actor_id, kind, from_actor_id, object_ap_id)
);

CREATE INDEX notifications_actor_active
    ON notifications (actor_id, is_dismissed, created_at DESC);

CREATE INDEX notifications_object_ap_id_idx
    ON notifications (object_ap_id)
    WHERE object_ap_id IS NOT NULL;

-- Mirrors the multi-user `trg_cascade_object_delete` PG trigger.
-- Cleans up text-AP-ID cross-references (likes/announces/notifications) on
-- object deletion. These tables can hold remote AP IDs that have no row in
-- `objects`, so a real FK constraint isn't viable.

CREATE TRIGGER trg_cascade_object_delete
BEFORE DELETE ON objects
FOR EACH ROW
BEGIN
    DELETE FROM likes         WHERE object_ap_id = OLD.ap_id;
    DELETE FROM announces     WHERE object_ap_id = OLD.ap_id;
    DELETE FROM notifications WHERE object_ap_id = OLD.ap_id;
END;
